version: '3.8'


services:

  db-data:
    image: mysql:latest
    environment:
      MYSQL_PASSWORD: example
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: admin
      MYSQL_DATABASE: amazon
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql

  flask:
    build: ./app
    links:
      - db-data
    volumes:
      - ./app:/usr/src/app
    ports:
      - 5000:5000

volumes:
  mysql:
