version: '3.8'


services:

  db-data:
    image: mysql:latest
    env_file:
     - .env
    environment:
      - NODE_ENV
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/:ro

  flask:
    build: ./app
    depends_on:
      - db-data
    volumes:
      - ./app:/usr/src/app
    ports:
      - 5000:5000

volumes:
  mysql:
