version: '3.8'


services:

  db-data:
    image: mysql:latest
    environment:
      - NODE_ENV
    ports:
      - 3351:3306
    volumes:
      - mysql:/var/lib/mysql

  flask:
    build: ./app
    depends_on:
      - db-data
    volumes:
      - ./app:/usr/src/app
    ports:
      - 5000:5000

volumes:
  mysql:
